shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 323 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- delay overides the delay

shared.scr = [[
[wra0] p [wrd0] [raQ9] d f G [rfQ9]
d [wta0] p [wtd0] [tea0] p o [ute0]
[wra0] p [wrd0] [raQ9] d f G [rfQ9]
d [wta0] p [wtd0] [tea0] p o [ute0]
[wr0] p a p p p [wrp0] [rpQ9]
o p o p o p o p
a [raQ9] [wta0] p a p p p
[wtp0] [tpe0] o p o p o p
o p p o u [ute0] [wur0] G
h h G G f [wrG0] [rfQ9] f
f d d d a a a p
[rQ9] a s [wt0] a o p p
o [wt0] [yte0] u h f [te0] a
[wtf0] f f h G [eQ9] d a
p [wrf0] f f f h j [rQ9]
h G k h j k [wrf0] d
f [wrd0] f d [wra0] d f [rQ9]
G f [rdQ9] a [raQ9] p [wt0] a
[wt0] d f G [wtf0] d [tea0] p
p [te0] u [te0] [wrf0] d f [wrd0]
f d [wra0] d f [rQ9] G f
[rdQ9] a [raQ9] p [wt0] a [wt0] d
f G [wtf0] d [tea0] p p [te0]
u f [the0] k [wt0] f h [wtk0]
f [wth0] k [jeQ9] j h [jeQ9] h
f d [feQ9] [wrh0] [wrh0] G d [wr0]
f [rQ9] [rfQ9] f d a [rQ9] [wtf0]
d f [wtd0] f d [wta0] d f
[eQ9] G f [edQ9] a [eaQ9] p [wr0]
a [wr0] d f G [wrf0] d [raQ9]
p p [rQ9] u [rQ9] [wra0] p [wrd0]
[raQ9] d f G [rfQ9] d [wta0] p
[wtd0] [tea0] p o [ute0] [wr0] p a
p p p [wrp0] [rpQ9] o p o
p o p o p a [rQ9] h
[wtf0] p a p p p [wtp0] [tpe0]
o p o p o p o p
p o u [ute0] [wur0] G h h
G G f [wrG0] [rfQ9] f f d
d d a a a p [rQ9] a
s [wt0] a a d f [wt0] [tfe0]
d f d a k j h f
d [tfe0] a [wtf0] f f h G
[eQ9] d a p [wrf0] f f f
h j [rQ9] h G k h j
k [wrf0] d f [wrd0] f d [wra0]
d f [rQ9] G f [rdQ9] a [raQ9]
p [wt0] a [wt0] d f G [wtf0]
d [tea0] p p [te0] u [te0] [wrf0]
d f [wrd0] f d [wra0] d f
[rQ9] G f [rdQ9] a [raQ9] p [wt0]
a [wt0] d f G [wtf0] d [tea0]
p p [te0] u f [the0] k [wt0]
f h [wtk0] f [wth0] k [jeQ9] j
h [jeQ9] h f d [feQ9] [wrh0] [wrh0]
G d [wr0] f [rQ9] [rfQ9] f d
a [rQ9] [wtf0] d f [wtd0] f d
[wta0] d f [eQ9] G f [edQ9] a
[eaQ9] p [wr0] a [wr0] d f G
[wrf0] d [raQ9] p p [rQ9] u [rQ9]
[wtk0] h f k [jeQ9] G d j
[wrj0] [wrj9] k z x [wtf0] G h
k j [eQ9] h G d f f
[wr0] k [rjQ(] h G f D [wrf0]
d [wrf0] d f [wr0] d [wra0] d
f [rQ9] G [rfQ9] d a [rQ9] [raQ9]
p [wt0] a [wt0] d [wtf0] G [wtf0]
d [tea0] p [tpe0] [ute0] [te0] [wrf0] d
[wrf0] d f [wr0] d [wrf0] h k
[rQ9] j [rjQ9] h k [rQ9] [rkQ9] l
[wt0] k j [wt0] d [wtf0] G [wtf0]
d [tea0] p [tpe0] [ute0] f [the0] k
[wt0] f h [wtk0] f [wth0] k [jeQ9]
j h [jeQ9] h f d [feQ9] [wrh0]
[wrh0] G d [wr0] f [rQ9] [rfQ9] f
d a [rQ9] [wtf0] d f [wtd0] f
d [wta0] d f [eQ9] G f [edQ9]
a [eaQ9] p [wr0] a [wr0] d f
G [wrf0] d [raQ9] p p [rQ9] u
[rQ9] [wra0] [wr0] p [wrd0] a [rQ9] [rdQ9]
f G [rfQ9] d [wta0] [wt0] p [wtd0]
a [te0] [tpe0] o [ute0] [wra0] [wr0] p
[wrd0] a [rQ9] [rdQ9] f G [rfQ9] d
[wta0] [wt0] p [wtd0] a [te0] [tpe0] o
[ute0] [f30]
]]
